<div class="error-form-container">
<form id="error-form" action="" enctype="multipart/form-data">
    <h1>Сообщите нам об ошибке</h1>
    <div class="form-inner">
        <label>ФИО</label>
        <input type="text" required name="fio">
        
    </div>
    <div class="form-inner">
        <label>Email</label>
        <input type="email" required name="email">
        
        </div>
    <div class="form-inner">
        <label>Телефон</label>
        <input type="phone" required name="phone">
        </div>
    <div class="form-inner">
        <label>Информация об ошибке</label>
        <input type="text" required name="info">
    </div>
    <div class="form-inner__file">
        <label>Скриншот ошибки</label>
        <input type="file" name="file" multiple accept="image/*,image/jpeg">
    </div>
    <div id="form-error" class="form-inner">
        
    </div>
<input class="form-button" type="submit" value="Отправить">
</form>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>
 $(document).ready(function () {
    $("#error-form").submit(function () {
        // Получение ID формы
        var formID = $(this).attr('id');
        // Добавление решётки к имени ID
        var formNm = new FormData($('#' + formID)[0]);
        var info = $('#form-error');
        $.ajax({
            processData: false,
            contentType: false,
            type: "POST",
            url: 'https://l103555.hostru08.fornex.host/test.site/input.php',
            data: formNm,
            beforeSend: function () {
                // Вывод текста в процессе отправки
                $(info).html('<p style="text-align:center">Отправка...</p>');
            },
            success: function (data) {
                // Вывод текста результата отправки
                $(info).html('<p style="text-align:center">'+data+'</p>');
            },
            error: function (jqXHR, text, error) {
                // Вывод текста ошибки отправки
                $(info).html(error);
            }
        });
        return false;
    });
});

</script>